{
    'name': "Chapter 11",
    'summary': "Creating a 'Add Custom Taco' action on SO lines",
    'author': "Too Good Taco IT Department",
    'website': "https://www.toogoodtaco.com",
    'license': 'AGPL-3',
    'version': '14.0.1.0.0',
    'category': 'Technical/Training',
    'depends': [
        'product',
        'uom',
        'sale',
        'sale_management',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/product_taco_ingredients.xml',
        'data/custom_taco.xml',
        'report/sale_report.xml',
        'views/res_config_settings.xml',
        'views/assets.xml',
        'views/product.xml',
        'views/sale_order.xml',
        'views/assets.xml',
        'wizards/add_custom_taco_wizard.xml',
    ],
    'installable': True,
    'application': False,
}
